name: CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php_version }}
    strategy:
      matrix:
        php_version: ["8.2", "8.1"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: php --version
        
  mongo:
    runs-on: ubuntu-latest
    container:
      image: mongo:${{ matrix.mongodb_version }}
    strategy:
      matrix:
        mongodb_version: ["4.2", "4.4"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: mongod -version

